<?php
require_once __DIR__.'/../../../app/app.php';PageGuard::capability(Capabilities::SALES_RECORD);
$db=Database::pdo();$O=new Models\OrderModel($db);$isStaff=TenantContext::role()==='staff';$base=public_url(($isStaff?'staff':'super').'/restaurant/');
$open=$O->openOrders(['channels'=>['restaurant']]);$st=$db->prepare("SELECT o.*,u.username opened_by_name,(SELECT COUNT(*) FROM order_items i WHERE i.order_id=o.id) item_count FROM orders o LEFT JOIN users u ON u.id=o.opened_by WHERE o.tenant_id=? AND o.channel='restaurant' AND o.status<>'void' ORDER BY o.id DESC LIMIT 100");$st->execute([TenantContext::tenantId()]);$orders=$st->fetchAll();
$page_title='Restaurant Orders';ob_start();?>
<div class="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-4"><div><h1 class="h5 fw-bold mb-1">Restaurant orders</h1><p class="text-muted small mb-0">Separate from credit sales. Paid orders still appear in the global Sales and Reports pages.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary btn-sm" href="<?php echo $base;?>held.php">Held orders</a><a class="btn btn-primary btn-sm" href="<?php echo $base;?>new.php">New order</a></div></div>
<div class="row g-3 mb-4"><div class="col-sm-4"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted text-uppercase fw-semibold">Open orders</small><div class="h4 fw-bold mb-0"><?php echo count($open);?></div></div></div></div><div class="col-sm-4"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted text-uppercase fw-semibold">Awaiting payment</small><div class="h4 fw-bold text-warning mb-0">KES <?php echo number_format(array_sum(array_map(fn($o)=>max(0,(float)$o['total']-(float)$o['amount_paid']),$open)),2);?></div></div></div></div></div>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Order</th><th>Table / customer</th><th>Opened by</th><th>Items</th><th>Status</th><th class="text-end">Total</th><th></th></tr></thead><tbody><?php if(!$orders):?><tr><td colspan="7" class="text-center text-muted py-4">No restaurant orders yet.</td></tr><?php else:foreach($orders as $o):?><tr><td><strong><?php echo htmlspecialchars($o['receipt_number']);?></strong><small class="d-block text-muted"><?php echo htmlspecialchars($o['created_at']);?></small></td><td><?php echo htmlspecialchars($o['table_name']?:'Walk-in');?></td><td><?php echo htmlspecialchars($o['opened_by_name']??'—');?></td><td><?php echo (int)$o['item_count'];?></td><td><span class="badge <?php echo $o['status']==='paid'?'bg-success':'bg-warning text-dark';?>"><?php echo htmlspecialchars(ucfirst($o['status']));?></span></td><td class="text-end fw-semibold">KES <?php echo number_format((float)$o['total'],2);?></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="<?php echo $base;?>view.php?id=<?php echo (int)$o['id'];?>">View</a><?php if($o['status']==='open'&&($isStaff?TenantContext::can(Capabilities::PAYMENTS_PROCESS):true)):?><a class="btn btn-sm btn-primary" href="<?php echo $base;?>pay.php?id=<?php echo (int)$o['id'];?>">Pay</a><?php endif;?></td></tr><?php endforeach;endif;?></tbody></table></div></div>
<?php $content=ob_get_clean();$__layout=$isStaff?'staff':'tenants';include __DIR__.'/../../templates/'.$__layout.'/layout.php';
