<?php
require_once __DIR__.'/../../../app/app.php';
PageGuard::capability(Capabilities::SALES_RECORD);
$db=Database::pdo();$P=new Models\ProductModel($db);$H=new Models\HeldOrderModel($db);$O=new Models\OrderModel($db);
$isStaff=TenantContext::role()==='staff';$base=public_url(($isStaff?'staff':'super').'/restaurant/');
$products=$P->sellableMenu();$error='';$resumeId=(int)($_GET['resume']??$_POST['held_id']??0);$initial=[];
if($resumeId){foreach($H->items($resumeId) as $line)$initial[]=['product_id'=>(int)$line['product_id'],'quantity'=>(float)$line['quantity']];}
if($_SERVER['REQUEST_METHOD']==='POST'){
  $items=json_decode((string)($_POST['cart']??'[]'),true);if(!is_array($items))$items=[];
  $payload=['customer_name'=>trim((string)($_POST['table_name']??'')),'staff_id'=>TenantContext::userId(),'items'=>$items,'context'=>'restaurant'];
  if(($_POST['action']??'')==='hold'){$res=$H->hold($payload);if($res['ok']){if($resumeId)$H->discard($resumeId);$_SESSION['flash']['success']='Restaurant order held.';header('Location: '.$base.'held.php');exit;}$error=$res['errors']['_']??'Could not hold order.';}
  else{$res=$O->open(['channel'=>'restaurant','table_name'=>$payload['customer_name'],'opened_by'=>TenantContext::userId(),'items'=>$items]);if($res['ok']){if($resumeId)$H->discard($resumeId);$_SESSION['flash']['success']='Restaurant order '.$res['receipt_number'].' opened.';header('Location: '.$base.'view.php?id='.(int)$res['order_id']);exit;}$error=$res['errors']['_']??($res['errors']['table_name']??'Could not place order.');}
}
$page_title='New Restaurant Order';ob_start();?>
<div class="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-4"><div><h1 class="h5 fw-bold mb-1">New restaurant order</h1><p class="text-muted small mb-0">Select menu items, then place or hold the order. Stock moves only when an order is placed.</p></div><a href="<?php echo $base;?>" class="btn btn-outline-secondary btn-sm">Open orders</a></div>
<?php if($error):?><div class="alert alert-danger"><?php echo htmlspecialchars($error);?></div><?php endif;?>
<form method="post" id="restaurantForm"><input type="hidden" name="cart" id="restaurantCart"><input type="hidden" name="held_id" value="<?php echo $resumeId;?>">
<div class="row g-4"><div class="col-lg-8"><div class="card border-0 shadow-sm"><div class="card-body"><input id="menuSearch" class="form-control mb-3" placeholder="Search food, drink or category"><div class="row g-3" id="menuGrid">
<?php foreach($products as $p):?><div class="col-sm-6 col-xl-4 menu-product" data-search="<?php echo htmlspecialchars(strtolower($p['name'].' '.($p['category_name']??'')),ENT_QUOTES);?>"><button type="button" class="card w-100 h-100 text-start border p-3 bg-white add-menu" data-id="<?php echo (int)$p['id'];?>"><span class="fw-semibold"><?php echo htmlspecialchars($p['name']);?></span><small class="text-muted"><?php echo htmlspecialchars($p['category_name']??'Menu');?> · stock <?php echo number_format((float)$p['quantity'],2);?></small><strong class="text-primary mt-2">KES <?php echo number_format((float)$p['retail_price'],2);?></strong></button></div><?php endforeach;?>
<?php if(!$products):?><div class="col-12 text-center text-muted py-4">No available menu items. Create them under Restaurant Menu.</div><?php endif;?></div></div></div></div>
<div class="col-lg-4"><div class="card border-0 shadow-sm sticky-top" style="top:15px"><div class="card-body"><label class="form-label">Table / customer</label><input name="table_name" class="form-control mb-3" placeholder="Table 4 or customer name" required><h2 class="h6 fw-bold">Order items</h2><div id="cartLines" class="mb-3"></div><div class="d-flex justify-content-between border-top pt-3 mb-3"><strong>Total</strong><strong id="cartTotal">KES 0.00</strong></div><div class="d-grid gap-2"><button name="action" value="place" class="btn btn-primary">Place order</button><button name="action" value="hold" class="btn btn-outline-secondary">Hold order</button></div></div></div></div></div></form>
<script>
(function(){var products=<?php echo json_encode(array_column(array_map(fn($p)=>['id'=>(int)$p['id'],'name'=>$p['name'],'price'=>(float)$p['retail_price'],'stock'=>(float)$p['quantity']],$products),null,'id');?>,cart={};(<?php echo json_encode($initial);?>).forEach(function(x){cart[x.product_id]=x.quantity});var lines=document.getElementById('cartLines'),input=document.getElementById('restaurantCart');
function render(){var html='',total=0,out=[];Object.keys(cart).forEach(function(id){var p=products[id],q=cart[id];if(!p||q<=0)return;total+=p.price*q;out.push({product_id:+id,quantity:q,price_type:'retail'});html+='<div class="d-flex align-items-center gap-2 border-bottom py-2"><div class="flex-grow-1"><strong>'+p.name+'</strong><small class="d-block text-muted">KES '+p.price.toFixed(2)+'</small></div><button type="button" class="btn btn-sm btn-outline-secondary" data-dec=\"'+id+'\">−</button><span>'+q+'</span><button type="button" class="btn btn-sm btn-outline-secondary" data-inc=\"'+id+'\">+</button></div>';});lines.innerHTML=html||'<div class="text-muted small py-3">No items selected.</div>';input.value=JSON.stringify(out);document.getElementById('cartTotal').textContent='KES '+total.toFixed(2);}
document.addEventListener('click',function(e){var b=e.target.closest('.add-menu,[data-inc],[data-dec]');if(!b)return;var id=b.dataset.id||b.dataset.inc||b.dataset.dec,p=products[id];if(!p)return;if(b.dataset.dec!==undefined)cart[id]=Math.max(0,(cart[id]||0)-1);else if((cart[id]||0)<p.stock)cart[id]=(cart[id]||0)+1;render();});document.getElementById('menuSearch').addEventListener('input',function(){var q=this.value.toLowerCase();document.querySelectorAll('.menu-product').forEach(function(x){x.style.display=x.dataset.search.indexOf(q)>=0?'':'none';});});document.getElementById('restaurantForm').addEventListener('submit',function(e){if(!JSON.parse(input.value||'[]').length){e.preventDefault();alert('Add at least one menu item.');}});render();})();
</script>
<?php $content=ob_get_clean();$__layout=$isStaff?'staff':'tenants';include __DIR__.'/../../templates/'.$__layout.'/layout.php';
