<?php
require_once __DIR__.'/../../../app/app.php';PageGuard::capability(Capabilities::SALES_RECORD);
$db=Database::pdo();$O=new Models\OrderModel($db);$P=new Models\ProductModel($db);$id=(int)($_GET['id']??$_POST['id']??0);$order=$O->find($id);
if(!$order||($order['channel']??'')!=='restaurant'){http_response_code(404);exit('Restaurant order not found.');}
$isStaff=TenantContext::role()==='staff';$base=public_url(($isStaff?'staff':'super').'/restaurant/');$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&$order['status']==='open'){
 $pid=(int)($_POST['product_id']??0);$qty=max(0,(float)($_POST['quantity']??0));$res=$O->addItems($id,[['product_id'=>$pid,'quantity'=>$qty,'price_type'=>'retail']],TenantContext::userId());
 if($res['ok']){$_SESSION['flash']['success']='Item added to the restaurant order.';header('Location: '.$base.'view.php?id='.$id);exit;}$error=$res['errors']['_']??'Could not update order.';
}
$order=$O->find($id);$items=$O->items($id);$products=$P->sellableMenu();$due=max(0,(float)$order['total']-(float)($order['amount_paid']??0));$page_title='Restaurant Order';ob_start();?>
<div class="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-4"><div><a href="<?php echo $base;?>" class="small text-muted text-decoration-none">&larr; Restaurant orders</a><h1 class="h5 fw-bold mt-2 mb-1"><?php echo htmlspecialchars($order['receipt_number']);?></h1><p class="text-muted small mb-0"><?php echo htmlspecialchars($order['table_name']?:'Walk-in');?> · opened <?php echo htmlspecialchars($order['created_at']);?></p></div><div class="d-flex gap-2"><?php if($order['status']==='open'&&(!$isStaff||TenantContext::can(Capabilities::PAYMENTS_PROCESS))):?><a class="btn btn-primary" href="<?php echo $base;?>pay.php?id=<?php echo $id;?>">Process payment</a><?php endif;?><a class="btn btn-outline-secondary" href="<?php echo public_url(($isStaff?'staff':'super').'/orders/receipt.php?id='.$id);?>">Receipt</a></div></div>
<?php if($error):?><div class="alert alert-danger"><?php echo htmlspecialchars($error);?></div><?php endif;?>
<div class="row g-4"><div class="col-lg-8"><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Menu item</th><th class="text-end">Price</th><th class="text-end">Quantity</th><th class="text-end">Total</th></tr></thead><tbody><?php foreach($items as $item):?><tr><td class="fw-semibold"><?php echo htmlspecialchars($item['product_name']);?></td><td class="text-end">KES <?php echo number_format((float)$item['unit_price'],2);?></td><td class="text-end"><?php echo number_format((float)$item['quantity'],2);?></td><td class="text-end fw-semibold">KES <?php echo number_format((float)$item['line_total'],2);?></td></tr><?php endforeach;?></tbody><tfoot><tr><th colspan="3" class="text-end">Order total</th><th class="text-end">KES <?php echo number_format((float)$order['total'],2);?></th></tr><tr><th colspan="3" class="text-end">Balance due</th><th class="text-end text-warning">KES <?php echo number_format($due,2);?></th></tr></tfoot></table></div></div></div>
<div class="col-lg-4"><?php if($order['status']==='open'):?><form method="post" class="card border-0 shadow-sm"><div class="card-body"><input type="hidden" name="id" value="<?php echo $id;?>"><h2 class="h6 fw-bold">Add to ongoing order</h2><label class="form-label">Menu item</label><select name="product_id" class="form-select mb-2" required><option value="">Choose item</option><?php foreach($products as $p):?><option value="<?php echo (int)$p['id'];?>"><?php echo htmlspecialchars($p['name']);?> — KES <?php echo number_format((float)$p['retail_price'],2);?></option><?php endforeach;?></select><label class="form-label">Quantity</label><input name="quantity" type="number" min="0.01" step=".01" value="1" class="form-control mb-3" required><button class="btn btn-outline-primary w-100">Add item</button></div></form><?php else:?><div class="card border-0 shadow-sm"><div class="card-body text-center"><i class="fas fa-check-circle text-success fa-2x mb-2"></i><h2 class="h6">Order paid</h2><p class="small text-muted mb-0">This sale is available in global Sales and Reports.</p></div></div><?php endif;?></div></div>
<?php $content=ob_get_clean();$__layout=$isStaff?'staff':'tenants';include __DIR__.'/../../templates/'.$__layout.'/layout.php';
