<?php
require_once __DIR__.'/../../../app/app.php';PageGuard::tenant();
$B=new Models\BranchModel(Database::pdo());$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action']??'';
 if($action==='create'){$r=$B->createBranch($_POST);if(!$r['ok'])$error=$r['error'];else{BranchContext::select((int)$r['id']);$_SESSION['flash']['success']='Branch created and selected.';header('Location: '.public_url('super/branches/'));exit;}}
 elseif($action==='select'&&BranchContext::select((int)$_POST['branch_id'])){header('Location: '.public_url('super/branches/'));exit;}
 elseif($action==='assign'){$B->assignStaff((int)$_POST['user_id'],(int)$_POST['branch_id']);$_SESSION['flash']['success']='Staff branch assignment updated.';header('Location: '.public_url('super/branches/'));exit;}
}
$branches=$B->list();$staff=$B->staff();$current=BranchContext::current();$page_title='Branches';ob_start();?>
<div class="d-flex justify-content-between align-items-start mb-3"><div><h1 class="h5 fw-bold mb-1">Branches & Inventory Sharing</h1><p class="small text-muted mb-0">Shared branches sell from one company balance. Separate branches keep their own stock quantities.</p></div><?php if($current):?><span class="badge bg-primary p-2">Working branch: <?php echo htmlspecialchars($current['name']);?></span><?php endif;?></div>
<?php if($error):?><div class="alert alert-danger"><?php echo htmlspecialchars($error);?></div><?php endif;?>
<div class="row g-4"><div class="col-lg-4"><form method="post" class="card border-0 shadow-sm"><input type="hidden" name="action" value="create"><div class="card-body"><h2 class="h6 fw-bold">Create branch</h2><label class="form-label small">Branch name</label><input class="form-control mb-2" name="name" required placeholder="Westlands"><label class="form-label small">Location</label><input class="form-control mb-2" name="location"><label class="form-label small">Inventory</label><select class="form-select mb-2" name="inventory_mode"><option value="shared">Share the main inventory</option><option value="independent">Keep a separate inventory</option></select><label class="form-check"><input class="form-check-input" type="checkbox" name="copy_inventory" value="1"><span class="form-check-label">Copy current quantities as opening stock</span></label><div class="form-text">For a separate new branch, leave this unchecked to start every product at zero.</div><button class="btn btn-primary w-100 mt-3">Create branch</button></div></form></div>
<div class="col-lg-8"><div class="card border-0 shadow-sm mb-4"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Branch</th><th>Inventory</th><th>Staff</th><th>Actions</th></tr></thead><tbody><?php foreach($branches as $b):?><tr><td><strong><?php echo htmlspecialchars($b['name']);?></strong><small class="d-block text-muted"><?php echo htmlspecialchars($b['location']?:'No location set');?></small></td><td><span class="badge <?php echo $b['inventory_mode']==='shared'?'bg-info':'bg-warning text-dark';?>"><?php echo $b['inventory_mode']==='shared'?'Shared':'Separate';?></span></td><td><?php echo (int)$b['staff_count'];?></td><td class="d-flex gap-2"><form method="post"><input type="hidden" name="action" value="select"><input type="hidden" name="branch_id" value="<?php echo (int)$b['id'];?>"><button class="btn btn-sm <?php echo (int)($current['id']??0)===(int)$b['id']?'btn-primary':'btn-outline-primary';?>"><?php echo (int)($current['id']??0)===(int)$b['id']?'Selected':'Work here';?></button></form><?php if($b['inventory_mode']==='independent'):?><a class="btn btn-sm btn-outline-secondary" href="<?php echo public_url('super/branches/stock.php?id='.(int)$b['id']);?>">Set stock</a><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div>
<form method="post" class="card border-0 shadow-sm"><input type="hidden" name="action" value="assign"><div class="card-body"><h2 class="h6 fw-bold">Assign staff to a branch</h2><div class="row g-2"><div class="col-md-5"><select class="form-select" name="user_id" required><option value="">Choose staff</option><?php foreach($staff as $u):?><option value="<?php echo (int)$u['id'];?>"><?php echo htmlspecialchars($u['username']);?></option><?php endforeach;?></select></div><div class="col-md-5"><select class="form-select" name="branch_id" required><option value="">Choose branch</option><?php foreach($branches as $b):?><option value="<?php echo (int)$b['id'];?>"><?php echo htmlspecialchars($b['name']);?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Assign</button></div></div></div></form></div></div>
<?php $content=ob_get_clean();include __DIR__.'/../../templates/tenants/layout.php';
