<?php
require_once __DIR__.'/../../../app/app.php';PageGuard::tenant();$db=Database::pdo();$B=new Models\BranchModel($db);$branchId=(int)($_GET['id']??$_POST['branch_id']??0);
$st=$db->prepare("SELECT *,title name FROM branches WHERE id=? AND tenant_id=? AND inventory_mode='independent'");$st->execute([$branchId,TenantContext::tenantId()]);$branch=$st->fetch();if(!$branch){http_response_code(404);exit('Separate-inventory branch not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'){foreach((array)($_POST['quantity']??[]) as $pid=>$qty)$B->setStock($branchId,(int)$pid,max(0,(float)$qty));$_SESSION['flash']['success']='Branch inventory balances saved.';header('Location: '.public_url('super/branches/stock.php?id='.$branchId));exit;}
$st=$db->prepare('SELECT p.id,p.name,p.unit,p.quantity company_quantity,COALESCE(bs.quantity,0) branch_quantity FROM products p LEFT JOIN branch_stock bs ON bs.tenant_id=p.tenant_id AND bs.product_id=p.id AND bs.branch_id=? WHERE p.tenant_id=? AND COALESCE(p.is_menu_item,0)=0 ORDER BY p.name');$st->execute([$branchId,TenantContext::tenantId()]);$products=$st->fetchAll();$page_title='Branch Inventory';ob_start();?>
<div class="d-flex justify-content-between align-items-start mb-3"><div><h1 class="h5 fw-bold mb-1"><?php echo htmlspecialchars($branch['name']);?> inventory</h1><p class="small text-muted mb-0">These balances are used by POS sales at this separate-inventory branch.</p></div><a class="btn btn-outline-secondary btn-sm" href="<?php echo public_url('super/branches/');?>">Back to branches</a></div>
<form method="post"><input type="hidden" name="branch_id" value="<?php echo $branchId;?>"><div class="card border-0 shadow-sm"><div class="card-body border-bottom"><input id="stockSearch" class="form-control" placeholder="Search products"></div><div class="table-responsive"><table class="table table-bordered mb-0"><thead><tr><th>Product</th><th>Unit</th><th class="text-end">Main/shared balance</th><th style="width:190px">This branch balance</th></tr></thead><tbody><?php foreach($products as $p):?><tr class="stock-row" data-name="<?php echo htmlspecialchars(strtolower($p['name']),ENT_QUOTES);?>"><td class="fw-semibold"><?php echo htmlspecialchars($p['name']);?></td><td><?php echo htmlspecialchars($p['unit']);?></td><td class="text-end text-muted"><?php echo number_format((float)$p['company_quantity'],2);?></td><td><input class="form-control form-control-sm text-end" name="quantity[<?php echo (int)$p['id'];?>]" type="number" min="0" step=".01" value="<?php echo htmlspecialchars((string)(float)$p['branch_quantity']);?>"></td></tr><?php endforeach;?></tbody></table></div><div class="card-body text-end"><button class="btn btn-primary">Save branch stock</button></div></div></form>
<script>document.getElementById('stockSearch').addEventListener('input',function(){var q=this.value.toLowerCase();document.querySelectorAll('.stock-row').forEach(function(r){r.style.display=r.dataset.name.indexOf(q)>=0?'':'none';});});</script>
<?php $content=ob_get_clean();include __DIR__.'/../../templates/tenants/layout.php';
