<?php
require_once __DIR__.'/../../../app/app.php';PageGuard::capability(Capabilities::STOCK_ENTER);
$R=new Models\RestaurantInventoryModel(Database::pdo());$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){$res=$R->receive($_POST,(int)TenantContext::userId());if($res['ok']){$_SESSION['flash']['success']=number_format((float)$res['quantity'],2).' units added to restaurant stock.';header('Location: '.public_url('super/restaurant-stock/'));exit;}$error=$res['error'];}
$ingredients=$R->ingredients();$requestedPeriod=(string)($_GET['period']??'week');$period=in_array($requestedPeriod,['today','week','month'],true)?$requestedPeriod:'week';$summary=$R->summary($period);$page_title='Restaurant Stock';ob_start();?>
<div class="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-3"><div><h1 class="h5 fw-bold mb-1">Restaurant Stock</h1><p class="small text-muted mb-0">Record kitchen stock in packs and pieces. Recipe quantities are deducted when restaurant orders are placed.</p></div><a class="btn btn-outline-primary btn-sm" href="<?php echo public_url('super/menu/');?>">Food menu & recipes</a></div>
<?php if($error):?><div class="alert alert-danger"><?php echo htmlspecialchars($error);?></div><?php endif;?>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">Restaurant revenue</small><div class="h5 mb-0">KES <?php echo number_format((float)($summary['revenue']??0),2);?></div></div></div></div><div class="col-md-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">Ingredient cost</small><div class="h5 mb-0">KES <?php echo number_format((float)($summary['cogs']??0),2);?></div></div></div></div><div class="col-md-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">Gross profit</small><div class="h5 text-success mb-0">KES <?php echo number_format((float)($summary['profit']??0),2);?></div></div></div></div><div class="col-md-3"><form method="get" class="card border-0 shadow-sm h-100"><div class="card-body"><label class="small text-muted">Report period</label><select name="period" class="form-select form-select-sm mt-1" onchange="this.form.submit()"><option value="today" <?php echo $period==='today'?'selected':'';?>>Today</option><option value="week" <?php echo $period==='week'?'selected':'';?>>Last 7 days</option><option value="month" <?php echo $period==='month'?'selected':'';?>>Last 30 days</option></select></div></form></div></div>
<div class="row g-4"><div class="col-lg-4"><form method="post" class="card border-0 shadow-sm"><div class="card-body"><h2 class="h6 fw-bold">Receive kitchen stock</h2><label class="form-label small">Ingredient / stock name</label><input class="form-control mb-2" name="name" placeholder="Sausages" required><div class="row g-2"><div class="col-6"><label class="form-label small">Packages bought</label><input class="form-control" name="packages" type="number" min=".0001" step=".0001" placeholder="24" required></div><div class="col-6"><label class="form-label small">Units per package</label><input class="form-control" name="units_per_package" type="number" min=".0001" step=".0001" placeholder="20" required></div><div class="col-6"><label class="form-label small mt-2">Package name</label><input class="form-control" name="package_unit" value="packet" placeholder="packet, crate, kg"></div><div class="col-6"><label class="form-label small mt-2">Selling/recipe unit</label><input class="form-control" name="base_unit" value="stick" placeholder="stick, piece, gram"></div></div><label class="form-label small mt-2">Total buying cost (KES)</label><input class="form-control" name="total_cost" type="number" min="0" step=".01" required><div class="form-text">Example: 24 packets × 20 sticks records 480 sticks. Average cost is calculated automatically.</div><button class="btn btn-primary w-100 mt-3">Add stock</button></div></form></div>
<div class="col-lg-8"><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-bordered mb-0"><thead><tr><th>Kitchen stock</th><th>Packaging</th><th class="text-end">Remaining</th><th class="text-end">Avg cost/unit</th><th class="text-end">Value remaining</th></tr></thead><tbody><?php if(!$ingredients):?><tr><td colspan="5" class="text-center text-muted py-4">No restaurant stock recorded.</td></tr><?php else:foreach($ingredients as $i):?><tr><td class="fw-semibold"><?php echo htmlspecialchars($i['name']);?></td><td><?php echo number_format((float)$i['units_per_package'],2).' '.htmlspecialchars($i['base_unit']).' / '.htmlspecialchars($i['package_unit']);?></td><td class="text-end"><?php echo number_format((float)$i['quantity'],2).' '.htmlspecialchars($i['base_unit']);?></td><td class="text-end">KES <?php echo number_format((float)$i['avg_unit_cost'],2);?></td><td class="text-end">KES <?php echo number_format((float)$i['quantity']*(float)$i['avg_unit_cost'],2);?></td></tr><?php endforeach;endif;?></tbody></table></div></div></div></div>
<?php $content=ob_get_clean();include __DIR__.'/../../templates/tenants/layout.php';
