<?php
require_once __DIR__.'/../../../app/app.php';PageGuard::platform();$db=Database::pdo();$support=new TenantSupportService($db);
if(!$support->schemaReady()){$_SESSION['flash']['error']='Run support portal migrations first.';header('Location: '.public_url('platform/migrations/'));exit;}
$id=(int)($_GET['id']??$_POST['tenant_id']??0);$tenant=$support->tenant($id);if(!$tenant){http_response_code(404);exit('Business account not found.');}
$_SESSION['support_csrf']=$_SESSION['support_csrf']??bin2hex(random_bytes(24));$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!hash_equals((string)$_SESSION['support_csrf'],(string)($_POST['csrf']??''))){http_response_code(419);exit('This support form expired. Reload and try again.');}
  try{
    $action=(string)($_POST['action']??'save_access');
    if($action==='suspend'||$action==='reopen')$support->setStatus($id,$action==='reopen'?'active':'suspended',(int)TenantContext::userId());
    else $support->saveAccess($id,(array)($_POST['modules']??[]),(array)($_POST['pages']??[]),!empty($_POST['offline_enabled']),(int)TenantContext::userId());
    $_SESSION['flash']['success']=$action==='suspend'?'Business, staff portals and branches closed.':($action==='reopen'?'Business, staff portals and branches reopened.':'Business access settings saved. Online devices will refresh automatically.');
    header('Location: '.public_url('platform/tenants/edit.php?id='.$id));exit;
  }catch(Throwable $e){$error=$e->getMessage();}
}
$tenant=$support->tenant($id);$enabledModules=json_decode((string)($tenant['enabled_modules']??''),true);if(!is_array($enabledModules))$enabledModules=array_keys(TenantFeatures::MODULES);
$enabledPages=json_decode((string)($tenant['enabled_pages']??''),true);if(!is_array($enabledPages))$enabledPages=array_keys(TenantFeatures::PAGES);
$users=$db->prepare("SELECT u.username,u.email,u.is_active,r.role_name,b.title branch_name FROM users u LEFT JOIN roles r ON r.id=u.role_id LEFT JOIN branches b ON b.id=u.branch_id WHERE u.tenant_id=? ORDER BY u.id");$users->execute([$id]);$users=$users->fetchAll();
$page_title='Manage '.$tenant['name'];ob_start();?>
<div class="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-4"><div><a class="small text-decoration-none" href="<?php echo public_url('platform/tenants/');?>">← Businesses</a><h1 class="h4 fw-bold mt-2 mb-1"><?php echo htmlspecialchars($tenant['name']);?></h1><p class="text-muted mb-0"><?php echo htmlspecialchars($tenant['owner_email']??'No owner assigned');?> · <?php echo (int)$tenant['user_count'];?> users · <?php echo (int)$tenant['branch_count'];?> branches</p></div><span class="badge fs-6 <?php echo $tenant['status']==='active'?'bg-success':'bg-danger';?>"><?php echo htmlspecialchars(ucfirst($tenant['status']));?></span></div>
<?php if($error):?><div class="alert alert-danger"><?php echo htmlspecialchars($error);?></div><?php endif;?>
<form method="post" data-support-sync><input type="hidden" name="tenant_id" value="<?php echo $id;?>"><input type="hidden" name="csrf" value="<?php echo htmlspecialchars($_SESSION['support_csrf']);?>"><input type="hidden" name="action" value="save_access">
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h6 fw-bold">Connection and installation</h2><label class="form-check border rounded p-3 ps-5"><input class="form-check-input" type="checkbox" name="offline_enabled" value="1" <?php echo !empty($tenant['offline_enabled'])?'checked':'';?>><strong>Online + Offline installed POS</strong><small class="d-block text-muted">Allows local login/sales while disconnected. Support changes apply when the device reconnects.</small></label></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between"><div><h2 class="h6 fw-bold mb-1">Business features</h2><p class="small text-muted">Feature engines and their related workflows.</p></div><button type="button" class="btn btn-sm btn-outline-secondary" data-check-all="modules">Select all</button></div><div class="row g-2"><?php foreach(TenantFeatures::MODULES as $key=>$label):?><div class="col-md-6 col-xl-4"><label class="form-check border rounded p-3 ps-5 h-100"><input class="form-check-input" type="checkbox" name="modules[]" value="<?php echo $key;?>" <?php echo in_array($key,$enabledModules,true)?'checked':'';?>><strong><?php echo htmlspecialchars($label);?></strong></label></div><?php endforeach;?></div></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between"><div><h2 class="h6 fw-bold mb-1">Visible pages</h2><p class="small text-muted">Unchecked pages disappear from navigation and cannot be opened directly. With none selected, only the owner dashboard remains.</p></div><button type="button" class="btn btn-sm btn-outline-secondary" data-check-all="pages">Select all</button></div><div class="row g-2"><?php foreach(TenantFeatures::PAGES as $key=>$label):?><div class="col-md-6 col-xl-4"><label class="form-check border rounded p-2 ps-5 h-100"><input class="form-check-input" type="checkbox" name="pages[]" value="<?php echo $key;?>" <?php echo in_array($key,$enabledPages,true)?'checked':'';?>><?php echo htmlspecialchars($label);?></label></div><?php endforeach;?></div><button class="btn btn-primary mt-4">Save access settings</button></div></div></form>
<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white py-3"><strong>Current account users</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>User</th><th>Role</th><th>Branch</th><th>Status</th></tr></thead><tbody><?php foreach($users as $user):?><tr><td><?php echo htmlspecialchars($user['username']);?><small class="d-block text-muted"><?php echo htmlspecialchars($user['email']);?></small></td><td><?php echo htmlspecialchars($user['role_name']??'—');?></td><td><?php echo htmlspecialchars($user['branch_name']??'Shared / unassigned');?></td><td><?php echo !empty($user['is_active'])?'Active':'Inactive';?></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="card border-danger"><div class="card-body d-flex justify-content-between align-items-center gap-3"><div><strong><?php echo $tenant['status']==='active'?'Close this owner account':'Reopen this owner account';?></strong><p class="small text-muted mb-0"><?php echo $tenant['status']==='active'?'Immediately blocks the owner, every staff portal, API synchronization and every branch. Data is preserved.':'Restores tenant and branch access. Individual inactive users remain inactive.';?></p></div><form method="post" data-support-sync onsubmit="return confirm('<?php echo $tenant['status']==='active'?'Close this business and all linked access?':'Reopen this business and its branches?';?>');"><input type="hidden" name="tenant_id" value="<?php echo $id;?>"><input type="hidden" name="csrf" value="<?php echo htmlspecialchars($_SESSION['support_csrf']);?>"><input type="hidden" name="action" value="<?php echo $tenant['status']==='active'?'suspend':'reopen';?>"><button class="btn <?php echo $tenant['status']==='active'?'btn-danger':'btn-success';?>"><?php echo $tenant['status']==='active'?'Close account':'Reopen account';?></button></form></div></div>
<script>document.querySelectorAll('[data-check-all]').forEach(function(b){b.addEventListener('click',function(){var n=this.dataset.checkAll,boxes=document.querySelectorAll('input[name="'+n+'[]"]'),all=Array.prototype.every.call(boxes,function(x){return x.checked;});boxes.forEach(function(x){x.checked=!all;});this.textContent=all?'Select all':'Clear all';});});</script>
<?php $content=ob_get_clean();include __DIR__.'/../../templates/platform/layout.php';
