<?php
require_once __DIR__.'/../../../app/app.php';PageGuard::tenant();
$db=Database::pdo();$TM=new Models\TenantModel($db);$TM->ensureShopSchema();$tid=(int)TenantContext::tenantId();
if($_SERVER['REQUEST_METHOD']==='POST'){
 $modules=array_values(array_intersect(array_keys(TenantFeatures::MODULES),(array)($_POST['enabled_modules']??[])));
 $TM->updateSettings($tid,['enabled_modules'=>json_encode(array_merge($modules,[TenantFeatures::VERSION_MARKER])),'offline_enabled'=>!empty($_POST['offline_enabled'])?1:0]);
 TenantFeatures::reset();$_SESSION['flash']['success']='Features and connection mode updated.';header('Location: '.public_url('super/features/'));exit;
}
$tenant=$TM->find($tid)?:[];$enabled=json_decode((string)($tenant['enabled_modules']??''),true);if(!is_array($enabled))$enabled=array_keys(TenantFeatures::MODULES);elseif(!in_array(TenantFeatures::VERSION_MARKER,$enabled,true)&&!in_array('shop_pos',$enabled,true))$enabled[]='shop_pos';$offline=!empty($tenant['offline_enabled']);
$page_title='Features & Connection Mode';ob_start();?>
<div class="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-4"><div><h1 class="h5 fw-bold mb-1">Features & Online/Offline mode</h1><p class="text-muted small mb-0">Choose which modules this business uses and whether installed tills can continue selling without internet.</p></div><span class="badge <?php echo $offline?'bg-success':'bg-primary';?> p-2"><?php echo $offline?'Online + Offline':'Online only';?></span></div>
<form method="post"><div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h6 fw-bold">Connection mode</h2><div class="row g-3"><div class="col-md-6"><label class="border rounded p-3 d-flex gap-3 h-100"><input type="radio" class="form-check-input" name="offline_enabled" value="0" <?php echo !$offline?'checked':'';?>><span><strong>Online only</strong><small class="d-block text-muted">Login, products and sales always use the central MySQL server.</small></span></label></div><div class="col-md-6"><label class="border rounded p-3 d-flex gap-3 h-100"><input type="radio" class="form-check-input" name="offline_enabled" value="1" <?php echo $offline?'checked':'';?>><span><strong>Online + Offline</strong><small class="d-block text-muted">Installable POS, local staff unlock and queued sales that sync when internet returns.</small></span></label></div></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h6 fw-bold">Business modules</h2><p class="small text-muted">Core POS, Inventory, Sales, Payments and Settings always remain available.</p><div class="row g-3"><?php foreach(TenantFeatures::MODULES as $key=>$label):?><div class="col-md-6 col-xl-4"><label class="border rounded p-3 d-flex gap-2 h-100"><input class="form-check-input" type="checkbox" name="enabled_modules[]" value="<?php echo $key;?>" <?php echo in_array($key,$enabled,true)?'checked':'';?>><span class="fw-semibold"><?php echo htmlspecialchars($label);?></span></label></div><?php endforeach;?></div><button class="btn btn-primary mt-4">Save feature choices</button></div></div></form>
<?php if(!$offline):?><script>if('serviceWorker'in navigator){navigator.serviceWorker.getRegistrations().then(function(rs){rs.forEach(function(r){r.unregister();});});if(window.caches)caches.keys().then(function(keys){keys.filter(function(k){return k.indexOf('shop-pos-')===0;}).forEach(function(k){caches.delete(k);});});}</script><?php endif;?>
<?php $content=ob_get_clean();include __DIR__.'/../../templates/tenants/layout.php';
