<?php
require_once __DIR__.'/../../../app/app.php';PageGuard::capability(Capabilities::INVENTORY_VIEW);
$db=Database::pdo();$productId=(int)($_GET['product_id']??0);$q=trim((string)($_GET['q']??''));$status=in_array($_GET['status']??'',['in_stock','sold','returned'],true)?$_GET['status']:'';
$params=[TenantContext::tenantId()];$where='ps.tenant_id=?';
if($productId){$where.=' AND ps.product_id=?';$params[]=$productId;}if($status){$where.=' AND ps.status=?';$params[]=$status;}if($q!==''){$where.=' AND (ps.serial_number LIKE ? OR p.name LIKE ? OR o.receipt_number LIKE ?)';$like='%'.$q.'%';array_push($params,$like,$like,$like);}
$st=$db->prepare("SELECT ps.*,p.name product_name,o.receipt_number FROM product_serials ps JOIN products p ON p.id=ps.product_id AND p.tenant_id=ps.tenant_id LEFT JOIN order_items oi ON oi.id=ps.order_item_id LEFT JOIN orders o ON o.id=oi.order_id WHERE $where ORDER BY CASE ps.status WHEN 'in_stock' THEN 0 ELSE 1 END,ps.id DESC");$st->execute($params);$rows=$st->fetchAll();
$product=null;if($productId){$p=$db->prepare('SELECT id,name FROM products WHERE id=? AND tenant_id=? AND serial_tracking=1');$p->execute([$productId,TenantContext::tenantId()]);$product=$p->fetch();}
$page_title='Inventory Serial Numbers';ob_start();?>
<div class="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-3"><div><h1 class="h5 fw-bold mb-1"><i class="fas fa-fingerprint me-2 text-primary"></i><?php echo htmlspecialchars($product['name']??'Tracked Inventory Devices');?></h1><p class="small text-muted mb-0">Each serial/IMEI belongs to an inventory product. Checkout changes the exact device from In stock to Sold.</p></div><a class="btn btn-outline-secondary btn-sm" href="<?php echo public_url('super/inventory/');?>">Back to inventory</a></div>
<form method="get" class="card border-0 shadow-sm mb-3"><div class="card-body row g-2"><?php if($productId):?><input type="hidden" name="product_id" value="<?php echo $productId;?>"><?php endif;?><div class="col-md-8"><input class="form-control" name="q" value="<?php echo htmlspecialchars($q);?>" placeholder="Search serial, IMEI, device or receipt"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">All statuses</option><option value="in_stock" <?php echo $status==='in_stock'?'selected':'';?>>In stock</option><option value="sold" <?php echo $status==='sold'?'selected':'';?>>Sold</option><option value="returned" <?php echo $status==='returned'?'selected':'';?>>Returned</option></select></div><div class="col-md-1"><button class="btn btn-primary w-100">Find</button></div></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-bordered align-middle mb-0"><thead><tr><th>Device / product</th><th>Serial number / IMEI</th><th>Status</th><th>Receipt</th><th>Sold at</th><th>Recorded at</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="6" class="text-center text-muted py-4">No serial numbers match this view.</td></tr><?php else:foreach($rows as $row):?><tr><td class="fw-semibold"><?php echo htmlspecialchars($row['product_name']);?></td><td><code class="text-dark"><?php echo htmlspecialchars($row['serial_number']);?></code></td><td><span class="badge <?php echo $row['status']==='sold'?'bg-secondary':($row['status']==='in_stock'?'bg-success':'bg-warning text-dark');?>"><?php echo htmlspecialchars(ucwords(str_replace('_',' ',$row['status'])));?></span></td><td><?php echo htmlspecialchars($row['receipt_number']??'—');?></td><td><?php echo htmlspecialchars($row['sold_at']??'—');?></td><td><?php echo htmlspecialchars($row['created_at']);?></td></tr><?php endforeach;endif;?></tbody></table></div></div>
<?php $content=ob_get_clean();$__layout=TenantContext::role()==='staff'?'staff':'tenants';include __DIR__.'/../../templates/'.$__layout.'/layout.php';
