<?php
require_once __DIR__.'/../../../app/app.php';
if(empty($supportRouteMode)){header('Location: '.public_url('domain/support/'));exit;}
SupportGuard::auth();$db=Database::pdo();
$counts=['tenants'=>(int)$db->query('SELECT COUNT(*) FROM tenants')->fetchColumn(),'users'=>(int)$db->query('SELECT COUNT(*) FROM users WHERE COALESCE(is_active,1)=1')->fetchColumn(),'sales_today'=>0,'offline_pending'=>0];
try{$counts['sales_today']=(int)$db->query("SELECT COUNT(*) FROM orders WHERE status='paid' AND DATE(paid_at)=CURDATE()")->fetchColumn();}catch(Throwable $e){}
try{$counts['offline_pending']=(int)$db->query("SELECT COUNT(*) FROM orders WHERE client_uuid IS NOT NULL AND status='open'")->fetchColumn();}catch(Throwable $e){}
$sql="SELECT t.id,t.name,t.slug,t.status,t.offline_enabled,t.enabled_modules,t.created_at,u.username owner_name,u.email owner_email,
(SELECT COUNT(*) FROM users x WHERE x.tenant_id=t.id AND COALESCE(x.is_active,1)=1) user_count,
(SELECT COUNT(*) FROM orders o WHERE o.tenant_id=t.id AND o.status='paid' AND o.paid_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)) orders_30d,
(SELECT COALESCE(SUM(o.total),0) FROM orders o WHERE o.tenant_id=t.id AND o.status='paid' AND o.paid_at>=DATE_SUB(NOW(),INTERVAL 30 DAY)) revenue_30d,
(SELECT MAX(o.created_at) FROM orders o WHERE o.tenant_id=t.id) last_activity
FROM tenants t LEFT JOIN users u ON u.id=t.owner_user_id ORDER BY COALESCE(last_activity,t.created_at) DESC";
try{$tenants=$db->query($sql)->fetchAll();}catch(Throwable $e){$tenants=$db->query('SELECT * FROM tenants ORDER BY id DESC')->fetchAll();}
try{$activity=$db->query("SELECT o.receipt_number,o.channel,o.status,o.total,o.created_at,t.name tenant_name,u.username FROM orders o JOIN tenants t ON t.id=o.tenant_id LEFT JOIN users u ON u.id=o.opened_by ORDER BY o.id DESC LIMIT 20")->fetchAll();}catch(Throwable $e){$activity=[];}
$page_title='Platform Owner Dashboard';ob_start();?>
<div class="mb-4"><h1 class="h4 fw-bold mb-1">Platform Owner Dashboard</h1><p class="text-muted mb-0">See current businesses, users, sales flow and offline synchronization activity across the system.</p></div>
<div class="row g-3 mb-4"><?php foreach([['Businesses',$counts['tenants'],'building'],['Active users',$counts['users'],'users'],['Paid sales today',$counts['sales_today'],'receipt'],['Offline sales waiting',$counts['offline_pending'],'cloud-arrow-up']] as $c):?><div class="col-sm-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body d-flex justify-content-between"><div><small class="text-muted"><?php echo $c[0];?></small><div class="h3 mb-0"><?php echo number_format($c[1]);?></div></div><i class="fas fa-<?php echo $c[2];?> fa-2x text-primary opacity-50"></i></div></div></div><?php endforeach;?></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white py-3 d-flex justify-content-between"><strong>Businesses and current flow</strong><a class="btn btn-sm btn-outline-primary" href="<?php echo public_url('domain/support/businesses.php');?>">Manage account access</a></div><div class="table-responsive"><table class="table table-bordered align-middle mb-0"><thead><tr><th>Business</th><th>Owner</th><th>Status</th><th class="text-end">Users</th><th class="text-end">30-day orders</th><th class="text-end">30-day revenue</th><th>Connection</th><th>Last activity</th><th></th></tr></thead><tbody><?php foreach($tenants as $t):?><tr><td><strong><?php echo htmlspecialchars($t['name']);?></strong><small class="d-block text-muted"><?php echo htmlspecialchars($t['slug']??'');?></small></td><td><?php echo htmlspecialchars($t['owner_name']??'Not assigned');?><small class="d-block text-muted"><?php echo htmlspecialchars($t['owner_email']??'');?></small></td><td><span class="badge <?php echo ($t['status']??'')==='active'?'bg-success':'bg-danger';?>"><?php echo htmlspecialchars(ucfirst($t['status']??'unknown'));?></span></td><td class="text-end"><?php echo (int)($t['user_count']??0);?></td><td class="text-end"><?php echo (int)($t['orders_30d']??0);?></td><td class="text-end">KES <?php echo number_format((float)($t['revenue_30d']??0),2);?></td><td><span class="badge <?php echo !empty($t['offline_enabled'])?'bg-success':'bg-primary';?>"><?php echo !empty($t['offline_enabled'])?'Online + Offline':'Online only';?></span></td><td><?php echo htmlspecialchars($t['last_activity']??$t['created_at']??'—');?></td><td><a class="btn btn-sm btn-outline-dark" href="<?php echo public_url('domain/support/business.php?id='.(int)$t['id']);?>">Manage</a></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="card border-0 shadow-sm"><div class="card-header bg-white py-3"><strong>Latest system activity</strong></div><div class="table-responsive"><table class="table table-sm table-striped mb-0"><thead><tr><th>Time</th><th>Business</th><th>User</th><th>Flow</th><th>Receipt</th><th class="text-end">Amount</th></tr></thead><tbody><?php foreach($activity as $a):?><tr><td><?php echo htmlspecialchars($a['created_at']);?></td><td><?php echo htmlspecialchars($a['tenant_name']);?></td><td><?php echo htmlspecialchars($a['username']??'System');?></td><td><?php echo htmlspecialchars(ucfirst($a['channel']).' · '.$a['status']);?></td><td><?php echo htmlspecialchars($a['receipt_number']);?></td><td class="text-end">KES <?php echo number_format((float)$a['total'],2);?></td></tr><?php endforeach;?></tbody></table></div></div>
<?php $content=ob_get_clean();include __DIR__.'/../../templates/platform/layout.php';
