<?php
require_once __DIR__.'/../../../app/app.php';PageGuard::capability(Capabilities::INVENTORY_EDIT);
$db=Database::pdo();$P=new Models\ProductModel($db);$C=new Models\CategoryModel($db);$S=new Models\SubcategoryModel($db);$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  if(($_POST['action']??'')==='availability'){
    $db->prepare("UPDATE products SET status=? WHERE id=? AND tenant_id=? AND is_menu_item=1")->execute([!empty($_POST['available'])?'active':'archived',(int)$_POST['id'],TenantContext::tenantId()]);
    header('Location: '.public_url('super/menu/'));exit;
  }
  $catId=(int)($_POST['category_id']??0);$cat=$catId?$C->find($catId):null;
  if(!$cat||!in_array($cat['type'],['menu','product','subject'],true)){$error='Choose a valid menu or global category.';}else{
  $subId=(int)($_POST['subcategory_id']??0);$sub=$subId?$S->find($subId):null;if(!$sub||(int)$sub['category_id']!==$catId)$subId=0;
  $res=$P->create(['product_type'=>'product','name'=>$_POST['name']??'','category_id'=>$catId,'subcategory_id'=>$subId,'unit'=>'piece','quantity'=>max(0,(float)($_POST['available_quantity']??999999)),'buying_price'=>max(0,(float)($_POST['cost']??0)),'retail_price'=>max(0,(float)($_POST['price']??0)),'wholesale_price'=>max(0,(float)($_POST['price']??0)),'status'=>'active']);
  if($res['ok']){$db->prepare('UPDATE products SET is_menu_item=1 WHERE id=? AND tenant_id=?')->execute([$res['id'],TenantContext::tenantId()]);header('Location: '.public_url('super/menu/'));exit;}
  $error=$res['errors']['_']??'Could not create menu item.';
  }
}
$menuCategories=$C->all(['type'=>'menu'],'name ASC');$globalCategories=$C->all(['type'=>'product'],'name ASC');if(!$globalCategories)$globalCategories=$C->all(['type'=>'subject'],'name ASC');
$allCategoryIds=array_column(array_merge($menuCategories,$globalCategories),'id');$allSubs=[];foreach($allCategoryIds as $categoryId)foreach($S->listForCategory((int)$categoryId) as $sub)$allSubs[]=$sub;
$st=$db->prepare("SELECT p.*,c.name category_name,s.name subcategory_name FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN subcategories s ON s.id=p.subcategory_id WHERE p.tenant_id=? AND p.is_menu_item=1 ORDER BY c.name,s.name,p.name");$st->execute([TenantContext::tenantId()]);$items=$st->fetchAll();
$page_title='Restaurant Menu';ob_start();?>
<div class="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-3"><div><h1 class="h5 fw-bold">Food & Drink Menu</h1><p class="small text-muted">Use dedicated menu categories or reuse your global product categories. Paid restaurant orders enter the global Sales ledger.</p></div><a href="<?php echo public_url('super/categories/?type=menu');?>" class="btn btn-outline-primary btn-sm">Manage menu categories & subcategories</a></div>
<?php if($error):?><div class="alert alert-danger"><?php echo htmlspecialchars($error);?></div><?php endif;?>
<div class="row g-4"><div class="col-lg-4"><form method="post" class="card"><div class="card-body"><h2 class="h6 fw-bold">Add menu item</h2><label class="form-label small">Food / drink name</label><input name="name" required class="form-control mb-2"><label class="form-label small">Category</label><select name="category_id" id="menuCategory" required class="form-select mb-2"><option value="">Choose category</option><optgroup label="Menu categories"><?php foreach($menuCategories as $c):?><option value="<?php echo (int)$c['id'];?>"><?php echo htmlspecialchars($c['name']);?></option><?php endforeach;?></optgroup><optgroup label="Global product categories"><?php foreach($globalCategories as $c):?><option value="<?php echo (int)$c['id'];?>"><?php echo htmlspecialchars($c['name']);?></option><?php endforeach;?></optgroup></select><label class="form-label small">Subcategory <span class="text-muted">(optional)</span></label><select name="subcategory_id" id="menuSubcategory" class="form-select mb-2"><option value="">No subcategory</option><?php foreach($allSubs as $sub):?><option data-category="<?php echo (int)$sub['category_id'];?>" value="<?php echo (int)$sub['id'];?>"><?php echo htmlspecialchars($sub['name']);?></option><?php endforeach;?></select><div class="row g-2"><div class="col"><label class="form-label small">Selling price</label><input name="price" type="number" min="0" step=".01" required class="form-control"></div><div class="col"><label class="form-label small">Cost</label><input name="cost" type="number" min="0" step=".01" class="form-control"></div></div><label class="form-label small mt-2">Available portions</label><input name="available_quantity" type="number" min="0" step="1" value="999999" class="form-control"><button class="btn btn-primary w-100 mt-3">Add to menu</button></div></form></div>
<div class="col-lg-8"><div class="card"><div class="table-responsive"><table class="table table-bordered mb-0"><thead><tr><th>Menu item</th><th>Category</th><th>Subcategory</th><th class="text-end">Price</th><th class="text-end">Available</th><th>Status</th></tr></thead><tbody><?php if(!$items):?><tr><td colspan="6" class="text-center text-muted py-4">No menu items yet.</td></tr><?php else:foreach($items as $i):?><tr><td class="fw-semibold"><?php echo htmlspecialchars($i['name']);?></td><td><?php echo htmlspecialchars($i['category_name']?:'Menu');?></td><td><?php echo htmlspecialchars($i['subcategory_name']?:'—');?></td><td class="text-end">KES <?php echo number_format((float)$i['retail_price'],2);?></td><td class="text-end"><?php echo number_format((float)$i['quantity'],0);?></td><td><form method="post"><input type="hidden" name="action" value="availability"><input type="hidden" name="id" value="<?php echo (int)$i['id'];?>"><button name="available" value="<?php echo $i['status']==='active'?'0':'1';?>" class="btn btn-sm <?php echo $i['status']==='active'?'btn-success':'btn-outline-secondary';?>"><?php echo $i['status']==='active'?'Available':'Unavailable';?></button></form></td></tr><?php endforeach;endif;?></tbody></table></div></div></div></div>
<script>(function(){var c=document.getElementById('menuCategory'),s=document.getElementById('menuSubcategory');function filter(){var id=c.value;Array.from(s.options).forEach(function(o,i){if(!i)return;o.hidden=o.dataset.category!==id;});if(s.selectedOptions[0]&&s.selectedOptions[0].hidden)s.value='';}c.addEventListener('change',filter);filter();})();</script>
<?php $content=ob_get_clean();include __DIR__.'/../../templates/tenants/layout.php';
