<?php
require_once __DIR__.'/../../../app/app.php';PageGuard::capability(Capabilities::INVENTORY_EDIT);
$db=Database::pdo();$R=new Models\RestaurantInventoryModel($db);$pid=(int)($_GET['id']??$_POST['product_id']??0);
$st=$db->prepare('SELECT id,name,retail_price FROM products WHERE id=? AND tenant_id=? AND is_menu_item=1');$st->execute([$pid,TenantContext::tenantId()]);$product=$st->fetch();if(!$product){http_response_code(404);exit('Menu item not found.');}
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(($_POST['action']??'')==='variant'){$result=$R->saveVariant($pid,$_POST);if($result['ok']){header('Location: '.public_url('super/menu/recipe.php?id='.$pid.'&variant='.$result['id']));exit;}$error=$result['error'];}
 if(($_POST['action']??'')==='recipe'){$lines=[];foreach((array)($_POST['ingredient_id']??[]) as $i=>$iid)$lines[]=['ingredient_id'=>$iid,'quantity'=>$_POST['quantity'][$i]??0];$result=$R->saveRecipe((int)$_POST['variant_id'],$lines);if($result['ok']){$_SESSION['flash']['success']='Recipe saved. Stock will now be deducted automatically when this portion is ordered.';header('Location: '.public_url('super/menu/recipe.php?id='.$pid.'&variant='.(int)$_POST['variant_id']));exit;}$error=$result['error'];}
}
$variants=$R->variantsForProduct($pid);$selected=(int)($_GET['variant']??($variants[0]['id']??0));$recipe=$selected?$R->recipe($selected):[];$ingredients=$R->ingredients();$page_title='Menu Variants & Recipes';ob_start();?>
<div class="d-flex justify-content-between align-items-start mb-3"><div><h1 class="h5 fw-bold mb-1"><?php echo htmlspecialchars($product['name']);?></h1><p class="small text-muted mb-0">Create sizes such as ¼, ½ and Full. A platter is one variant with several recipe ingredients.</p></div><a class="btn btn-outline-secondary btn-sm" href="<?php echo public_url('super/menu/');?>">Back to menu</a></div>
<?php if($error):?><div class="alert alert-danger"><?php echo htmlspecialchars($error);?></div><?php endif;?>
<div class="row g-4"><div class="col-lg-4"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h6 fw-bold">Portions / variants</h2><div class="list-group mb-3"><?php foreach($variants as $v):?><a class="list-group-item list-group-item-action d-flex justify-content-between <?php echo $selected===(int)$v['id']?'active':'';?>" href="?id=<?php echo $pid;?>&variant=<?php echo (int)$v['id'];?>"><span><?php echo htmlspecialchars($v['label']);?></span><span>KES <?php echo number_format((float)$v['retail_price'],2);?></span></a><?php endforeach;?></div><form method="post"><input type="hidden" name="action" value="variant"><input type="hidden" name="product_id" value="<?php echo $pid;?>"><label class="form-label small">New portion name</label><input class="form-control mb-2" name="label" placeholder="¼, ½, Full or Family platter" required><label class="form-label small">Selling price</label><input class="form-control mb-2" name="price" type="number" min=".01" step=".01" required><button class="btn btn-outline-primary w-100">Add variant</button></form></div></div></div>
<div class="col-lg-8"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h6 fw-bold">Ingredients used per order</h2><?php if(!$selected):?><p class="text-muted">Add a variant first.</p><?php elseif(!$ingredients):?><div class="alert alert-warning">Record restaurant stock first, then return here to build the recipe.</div><?php else:?><form method="post" id="recipeForm"><input type="hidden" name="action" value="recipe"><input type="hidden" name="product_id" value="<?php echo $pid;?>"><input type="hidden" name="variant_id" value="<?php echo $selected;?>"><div id="recipeRows"><?php $rows=$recipe?:[['ingredient_id'=>'','quantity'=>'']];foreach($rows as $row):?><div class="row g-2 mb-2 recipe-row"><div class="col-7"><select name="ingredient_id[]" class="form-select" required><option value="">Choose ingredient</option><?php foreach($ingredients as $i):?><option value="<?php echo (int)$i['id'];?>" <?php echo (int)($row['ingredient_id']??0)===(int)$i['id']?'selected':'';?>><?php echo htmlspecialchars($i['name'].' ('.number_format((float)$i['quantity'],2).' '.$i['base_unit'].' left)');?></option><?php endforeach;?></select></div><div class="col-4"><input name="quantity[]" class="form-control" type="number" min=".0001" step=".0001" value="<?php echo htmlspecialchars((string)($row['quantity']??''));?>" placeholder="Qty used" required></div><div class="col-1"><button type="button" class="btn btn-outline-danger remove-row">×</button></div></div><?php endforeach;?></div><button type="button" class="btn btn-sm btn-outline-secondary" id="addRow">Add another ingredient</button><button class="btn btn-primary float-end">Save recipe</button></form><?php endif;?></div></div></div></div>
<script>(function(){var box=document.getElementById('recipeRows'),add=document.getElementById('addRow');if(!box||!add)return;add.onclick=function(){var row=box.querySelector('.recipe-row').cloneNode(true);row.querySelector('select').value='';row.querySelector('input').value='';box.appendChild(row);};box.onclick=function(e){if(e.target.classList.contains('remove-row')&&box.children.length>1)e.target.closest('.recipe-row').remove();};})();</script>
<?php $content=ob_get_clean();include __DIR__.'/../../templates/tenants/layout.php';
