<?php
require_once __DIR__.'/../../../app/app.php';PageGuard::capability(Capabilities::STOCK_ENTER);
$db=Database::pdo();$P=new Models\ProductModel($db);$S=new Models\ProductSerialModel($db);$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){$res=$S->add((int)($_POST['product_id']??0),(string)($_POST['serials']??''),!empty($_POST['increase_stock']));if($res['ok']){$_SESSION['flash']['success']=$res['count'].' serialized unit(s) recorded.';header('Location: '.public_url('super/serials/?product_id='.(int)$_POST['product_id']));exit;}$error=$res['error'];}
$products=$P->listWithMeta(true);$selected=(int)($_GET['product_id']??$_POST['product_id']??0);$rows=$selected?$S->forProduct($selected):[];$page_title='Serial Numbers';ob_start();?>
<div class="mb-3"><h1 class="h5 fw-bold">Serial numbers / IMEI</h1><p class="small text-muted">Record each unique technology unit. Serialized products require a serial confirmation before sale.</p></div>
<?php if($error):?><div class="alert alert-danger"><?php echo htmlspecialchars($error);?></div><?php endif;?>
<div class="row g-4"><div class="col-lg-5"><form method="post" class="card"><div class="card-body"><label class="form-label">Product</label><select name="product_id" class="form-select" required><option value="">Choose product</option><?php foreach($products as $p):?><option value="<?php echo (int)$p['id'];?>" <?php echo $selected===(int)$p['id']?'selected':'';?>><?php echo htmlspecialchars($p['name']);?></option><?php endforeach;?></select><label class="form-label mt-3">Serial numbers / IMEIs</label><textarea name="serials" class="form-control font-monospace" rows="8" required placeholder="One per line&#10;IMEI-001&#10;IMEI-002"></textarea><label class="form-check mt-2"><input class="form-check-input" type="checkbox" name="increase_stock" value="1" checked>These are newly received units—add them to stock quantity</label><button class="btn btn-primary mt-3">Record serials</button></div></form></div>
<div class="col-lg-7"><div class="card"><div class="table-responsive"><table class="table table-bordered mb-0"><thead><tr><th>Serial / IMEI</th><th>Status</th><th>Recorded</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="3" class="text-center text-muted py-4">Choose a product to view its serials.</td></tr><?php else:foreach($rows as $r):?><tr><td class="font-monospace fw-semibold"><?php echo htmlspecialchars($r['serial_number']);?></td><td><?php echo htmlspecialchars(str_replace('_',' ',$r['status']));?></td><td><?php echo htmlspecialchars($r['created_at']);?></td></tr><?php endforeach;endif;?></tbody></table></div></div></div></div>
<?php $content=ob_get_clean();include __DIR__.'/../../templates/tenants/layout.php';
